name: CI
on:
  push:
    branches:
      - '*'
    pull_request:
      - master
      - staging
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Test with Coverage
        run: npm run test:coverage
      
      - name: Send to codecov.io
        if: github.ref == 'refs/heads/master'
        run: bash <(curl -s https://codecov.io/bash)
